from enum import StrEnum

from pydantic import BaseModel


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    AI_NOT_CONFIGURED = "AI_NOT_CONFIGURED"
    AI_PROVIDER_ERROR = "AI_PROVIDER_ERROR"
    AI_PROVIDER_TIMEOUT = "AI_PROVIDER_TIMEOUT"
    UNSUPPORTED_REGION = "UNSUPPORTED_REGION"
    PLAN_NOT_AVAILABLE = "PLAN_NOT_AVAILABLE"
    POI_NOT_FOUND = "POI_NOT_FOUND"
    ROUTE_UNAVAILABLE = "ROUTE_UNAVAILABLE"
    MAP_PROVIDER_TIMEOUT = "MAP_PROVIDER_TIMEOUT"
    MAP_PROVIDER_ERROR = "MAP_PROVIDER_ERROR"
    MODEL_PROVIDER_TIMEOUT = "MODEL_PROVIDER_TIMEOUT"
    MODEL_OUTPUT_INVALID = "MODEL_OUTPUT_INVALID"
    PLAN_INCOMPLETE = "PLAN_INCOMPLETE"
    TIMELINE_MISMATCH = "TIMELINE_MISMATCH"
    REQUEST_CANCELLED = "REQUEST_CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AppError(BaseModel):
    """Stable error payload shared by domain and HTTP layers."""

    code: ErrorCode
    message: str
    retryable: bool
    details: dict[str, object] | None = None
